"""Add visit counter tables

Revision ID: 12ec4d85c414
Revises: 1a9868fdb022
Create Date: 2025-11-15 17:58:02.209823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ec4d85c414'
down_revision = '1a9868fdb022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_visit_counter',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_counter',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_counter')
    op.drop_table('daily_visit_counter')
    # ### end Alembic commands ###
