"""Fix user is_reporter default value

Revision ID: 2b3f5c8d9e01
Revises: 12ec4d85c414
Create Date: 2025-11-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3f5c8d9e01'
down_revision = '12ec4d85c414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update any NULL values to False (0)
    op.execute('UPDATE users SET is_reporter = 0 WHERE is_reporter IS NULL')
    op.execute('UPDATE users SET is_active = 1 WHERE is_active IS NULL')
    
    # For SQLite, we need to use batch operations to alter column defaults
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_reporter',
                              existing_type=sa.Boolean(),
                              server_default='0',
                              nullable=True)
        batch_op.alter_column('is_active',
                              existing_type=sa.Boolean(),
                              server_default='1',
                              nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_reporter',
                              existing_type=sa.Boolean(),
                              server_default=None,
                              nullable=True)
        batch_op.alter_column('is_active',
                              existing_type=sa.Boolean(),
                              server_default=None,
                              nullable=True)
    # ### end Alembic commands ###

