"""Add user password reset token

Revision ID: 357b2d83e654
Revises: 2b3f5c8d9e01
Create Date: 2025-11-23 12:33:11.436080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357b2d83e654'
down_revision = '2b3f5c8d9e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiration')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
