"""Add station_messages table

Revision ID: 9f0d28a67c6c
Revises: 357b2d83e654
Create Date: 2025-11-26 20:39:14.545570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0d28a67c6c'
down_revision = '357b2d83e654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_stations',
        sa.Column('message_id', sa.Integer(), nullable=False),
        sa.Column('station_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
        sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
        sa.PrimaryKeyConstraint('message_id', 'station_id')
    )

    conn = op.get_bind()

    enabled_stations = conn.execute(sa.text("""
        SELECT id FROM station WHERE enabled = 1
    """)).fetchall()

    enabled_station_ids = [row[0] for row in enabled_stations]

    messages = conn.execute(sa.text("""
        SELECT id, station_id FROM message
    """)).fetchall()

    for message_id, station_id in messages:
        if station_id is None:
            for sid in enabled_station_ids:
                conn.execute(sa.text("""
                    INSERT INTO message_stations (message_id, station_id)
                    VALUES (:m, :s)
                """), {"m": message_id, "s": sid})
        else:
            conn.execute(sa.text("""
                INSERT INTO message_stations (message_id, station_id)
                VALUES (:m, :s)
            """), {"m": message_id, "s": station_id})

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('station_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'station', ['station_id'], ['id'])

        pairs = conn.execute(sa.text("""
        SELECT message_id, MIN(station_id) as station_id
        FROM message_stations
        GROUP BY message_id
    """)).fetchall()

    for message_id, station_id in pairs:
        conn.execute(sa.text("""
            UPDATE message
            SET station_id = :s
            WHERE id = :m
        """), {"m": message_id, "s": station_id})


    op.drop_table('message_stations')
    # ### end Alembic commands ###
