"""Add initial migration

Revision ID: a260873697c9
Revises: 
Create Date: 2025-11-14 17:26:33.039341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a260873697c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('color', sa.String(), nullable=True),
        sa.Column('station_id', sa.Integer(), nullable=True),
        sa.Column('report_user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['report_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['station_id'], ['station.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ext_data',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('grid_state', sa.Boolean(), nullable=True),
        sa.Column('received_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.add_column('station', sa.Column('battery_capacity', sa.Integer(), nullable=True))
    op.add_column('station', sa.Column('new_start_operating_time', sa.DateTime(), nullable=True))
    op.execute('UPDATE station SET new_start_operating_time = datetime(start_operating_time, "unixepoch")')
    op.drop_column('station', 'start_operating_time')
    op.alter_column('station', 'new_start_operating_time', new_column_name='start_operating_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reporter', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_key')
        batch_op.drop_column('is_reporter')

    op.add_column('station', sa.Column('old_start_operating_time', sa.Integer(), nullable=True))
    op.execute('UPDATE station SET old_start_operating_time = strftime("%s", start_operating_time)')
    op.drop_column('station', 'start_operating_time')
    op.alter_column('station', 'old_start_operating_time', new_column_name='start_operating_time')
    op.drop_column('station', 'battery_capacity')


    op.drop_table('ext_data')
    op.drop_table('building')
    # ### end Alembic commands ###
